import type { Metadata } from 'next'
import Link from 'next/link'
import PageHero from '@/components/PageHero'

export const metadata: Metadata = {
  title: 'Celestial — AI Astrology App',
  description:
    'Celestial is an AI-powered astrology application delivering personalised birth chart readings and transit insights.',
}

const features = [
  {
    icon: '✦',
    title: 'Birth chart readings',
    description:
      'Full natal chart interpretation powered by precision ephemeris calculation and AI-generated narrative — covering sun, moon, rising, and all planetary placements.',
  },
  {
    icon: '◎',
    title: 'Transit insights',
    description:
      'Daily and weekly transit reports showing how current planetary movements interact with your natal chart, with clear, actionable guidance.',
  },
  {
    icon: '⟡',
    title: 'AI interpretation',
    description:
      'Nuanced, personalised readings generated by Claude AI — not template text. Every interpretation is written specifically for your chart.',
  },
  {
    icon: '◈',
    title: 'Reading history',
    description:
      'All your readings saved in one place. Return to past interpretations and track how cosmic themes evolve across time.',
  },
]

const techStack = ['React / Vite', 'FastAPI', 'Supabase', 'pyswisseph', 'Claude AI', 'Stripe']

export default function CelestialPage() {
  return (
    <>
      <PageHero
        eyebrow="Venture · Consumer App"
        title={<>Celestial — astrology <em className="italic font-normal text-accent">reimagined</em> with AI.</>}
        subtitle="Personalised birth chart readings and transit insights, powered by classical astrological calculation and modern large-language-model interpretation."
      />

      {/* ── Overview ── */}
      <section className="py-20 border-b border-rule">
        <div className="mx-auto max-w-6xl px-6 grid md:grid-cols-2 gap-16 items-start">
          <div className="space-y-4 text-mid font-light leading-relaxed">
            <p>
              Celestial bridges the depth of traditional Western astrology with the accessibility of AI-generated
              narrative. Rather than returning generic horoscope text, Celestial calculates your exact planetary
              positions using Swiss Ephemeris precision and then synthesises a personalised reading through
              Claude AI.
            </p>
            <p>
              The result is an interpretation that reads like it was written by an experienced astrologer who
              knows your chart — not a pre-written template matched to your sun sign.
            </p>
            <p>
              Celestial is currently in closed beta, refining the reading experience with a small group of
              early testers before a broader launch.
            </p>
          </div>
          <div>
            <p className="font-mono text-[0.65rem] tracking-[0.15em] uppercase text-mid mb-4">Built with</p>
            <div className="flex flex-wrap gap-2">
              {techStack.map((t) => (
                <span
                  key={t}
                  className="font-mono text-[0.65rem] tracking-[0.08em] uppercase bg-rule/60 text-mono px-3 py-1.5 rounded"
                >
                  {t}
                </span>
              ))}
            </div>
            <div className="mt-8 border border-rule p-5 rounded">
              <p className="font-mono text-[0.62rem] tracking-[0.14em] uppercase text-mid mb-1">Status</p>
              <p className="text-ink text-sm font-medium">Closed Beta</p>
              <p className="text-mid font-light text-xs mt-1">Operated by Connectum Labs Pty Ltd, Brisbane</p>
            </div>
          </div>
        </div>
      </section>

      {/* ── Features ── */}
      <section className="py-20 border-b border-rule">
        <div className="mx-auto max-w-6xl px-6">
          <p className="section-label">Features</p>
          <div className="grid sm:grid-cols-2 gap-px bg-rule border border-rule">
            {features.map((f) => (
              <div key={f.title} className="bg-paper p-8 hover:bg-white/60 transition-colors">
                <div className="text-2xl mb-4">{f.icon}</div>
                <h3 className="font-serif text-lg font-medium text-ink mb-2">{f.title}</h3>
                <p className="text-sm text-mid font-light leading-relaxed">{f.description}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ── CTA ── */}
      <section className="py-20">
        <div className="mx-auto max-w-6xl px-6 flex flex-col md:flex-row md:items-center justify-between gap-6">
          <div>
            <h2 className="font-serif text-2xl font-medium text-ink mb-1">Interested in Celestial?</h2>
            <p className="text-mid font-light text-sm">Get in touch to learn more or register your interest.</p>
          </div>
          <div className="flex items-center gap-3">
            <Link href="/contact" className="btn-primary shrink-0">Contact us →</Link>
            <Link href="/ventures" className="btn-outline shrink-0 text-sm">All ventures</Link>
          </div>
        </div>
      </section>
    </>
  )
}
